Add Quote Manager CLI Tool to main branch
Data-Epic/Quote-Manager-CLI-Precious pull request #1
Opened 2024-09-05 03:44 UTC by PrechyDev

### Overview
This PR introduces the initial commit for the Quote Manager CLI Tool project. It includes the complete setup for the project along with essential files, documentation, and configurations. The project was set up using Poetry and Click, and uses a Duckdb database.

### Components
1. **Project Files:**
   - Initial implementation of the Quote Manager CLI Tool with all core functionalities.
   - Included Python files for managing quotes, including database interactions and CLI commands.

2. **Documentation:**
   - Added `README.md` with detailed instructions on usage, setup, and configuration of the CLI tool.
   - Provided guidelines on setting the database path, using environment variables, and handling different database paths for development and testing.

3. **Makefile:**
   - Added a `Makefile` to facilitate common development tasks such as setting up the environment, running tests, linting, formatting, and building the package.

4. **Database Configuration:**
   - Included setup for database management with instructions for configuring the database file path.

5. **Logging**
   - Added general and error logging.

Please review the initial setup and let me know if there are any issues or further adjustments needed.

2024-09-07 18:43 UTC, elseagle requested changes
Fantastic PR, shows a lot of effort was put into this. Well done job.

I dropped some comments that could be applied across multiple files and some comments that are specific, but overall I think you did an excellent job.

2024-09-07 18:43 UTC, elseagle commented on .gitignore
> +*.db*
nit: add a new line to all the places you have this stop sign in this project

2024-09-07 18:43 UTC, elseagle commented on README.md
> +
clean out this empty spaces

2024-09-07 18:43 UTC, elseagle commented on quote_manager_cli/database.py
> +    text = Column(String, index=True)
Add some max length constraint to author and category

2024-09-07 18:43 UTC, elseagle commented on quote_manager_cli/database.py
> +def get_engine(url: str = DATABASE_URL) -> Any:
Haha, Don't use `Any`. Get the type and fix it there - if you can't get the type, mock it. You can apply this to all places you used it. (This was the comment I forgot to make on the call)

2024-09-07 18:43 UTC, elseagle commented on quote_manager_cli/database.py
> +def create_session(engine: Any) -> Optional[Session]:
Session isn't the only return type for this function. Also why not try to use `Union` in place of `Optional`? Apply this across all files

2024-09-07 18:43 UTC, elseagle commented on tests/test_quote_manager.py
> +    # Create an in-memory SQLite database for testing
Clean up the "botty" comments in your tests. Some of those things being commented on are obvious

2024-09-09 12:34 UTC, PrechyDev commented on quote_manager_cli/database.py
> +def create_session(engine: Any) -> Optional[Session]:
Added a type for engine. I found that `Optional` works as Union[Session, None] would work. But when I used it, I still had errors. to fix that, I just raised the errors instead of returning None.

2024-09-09 13:00 UTC, PrechyDev commented
Hi @elseagle.

I've made the necessary changes

2024-09-09 13:05 UTC, elseagle approved these changes
LGTM

2024-09-09 13:06 UTC, merged